version: "2"
services:
  wiredcraft-backend-dev-test:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/wired
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on: ["mongodb"]

  mongodb:
    image: mongo
    ports:
      - "27017:27017"