providers:
  logger:
    file: null
    pretty: true

  redis:
    host: 'localhost'
    port: 6379

  sequelize:
    dialect: 'mysql'
    host: 'localhost'
    username: 'root'
    password: 'root'
    database: 'barebone'
    logging: false

applications:
  http:
    address: 'localhost'
    port: 3000
